
spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "3.0"

loans:
  message: "This is the production APIs that relates to loans microservice"
  contactDetails:
    name: "Andrew - Production Lead"
    email: "andrew@gmail.com"
  callSupport:
    - (+65) 321-24345