
spring:
  config:
    activate:
      on-profile: "qa"

build:
  version: "2.0"

loans:
  message: "This is the QA APIs that relates to loans microservice"
  contactDetails:
    name: "Lawrence Chan - QA Lead"
    email: "chan@gmail.com"
  callSupport:
    - (+65) 321-24345